site_name: Green Algorithms calculator
site_url: https://sitename.example

# The top right box for Github
repo_url: https://github.com/GreenAlgorithms/green-algorithms-tool
repo_name: green-algorithm-tool

# The navigation tree
nav:
- Home: index.md
- Developer guide:
  - Getting started: developer_guide/getting_started.md
  - Pages:
    - Home page: developer_guide/pages/home_page.md
    - AI page: developer_guide/pages/ai_page.md
  - Blueprints:
    - Our implementation: developer_guide/blueprints/our_implementation.md
    - Form: developer_guide/blueprints/form.md
    - Import & Export: developer_guide/blueprints/import_export.md
    - Metrics: developer_guide/blueprints/metrics.md
    - Translation: developer_guide/blueprints/translation.md
- User guide:
  - Overview: user_guide/overview.md
  - Methodology: user_guide/methodology.md
- About:
  - Contributing: contribute.md
  - The team: team.md
  - License: license.md

plugins:
  - mkdocstrings # for automatically filling our markdown files
  - search # to use the built-in search bar

theme:
  name: material
  icon:
    # The top left logo of the header bar
    logo: fontawesome/solid/g
  favicon: assets/favicon.ico
  features:
    - navigation.tabs # the header navigation bar

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # To include tables in our documentation
  - tables
  # To allow clean code blocks in the documentation
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  # To allow the different kinds of admonition 
  # (detected by mkdocstrings and rendered by Material for MkDocs)
  - admonition
  - pymdownx.details
  # To use emojis and logos throughout the documentation
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
